PaloAltoNetworks/pan-os-upgrade-assurance

panos_upgrade_assurance/check_firewall.py

Please see the linked issue for details.
Fixes #45 
Locale setting forced in `__init__` function since multiple functions were affected.
Tested with python readiness check script in repo and custom Ansible module for check readiness.
Before the change:
```sh
$ LC_ALL=de_DE.utf-8 python examples/readiness_checks/run_readiness_checks.py -d fw.0003.test.net -u panadmin -p <password>
Traceback (most recent call last):
File "examples/readiness_checks/run_readiness_checks.py", line 90, in <module>
check_readiness = check_node.run_readiness_checks(
File "/Users/akose/Development/paloalto/pan-os-upgrade-assurance/panos_upgrade_assurance/check_firewall.py", line 734, in run_readiness_checks
check_result = self._check_method_mapping[check_type](**check_config)  # (**) would pass dict config values …
```

fix: datetime month parsing when non-English locale is set on host

---

docs/panos-upgrade-assurance/api/snapshot_compare.md
panos_upgrade_assurance/snapshot_compare.py

Validates only the requested keys in `thresholds` parameter for `session_stats` comparison.
Includes an enhancement to SnapshotCompare `key_checker` method to check if a list/set is a subset of both sides.
Currently, `session_stats` comparison expects all the keys to match between snapshots. This results in exception if PAN-OS API returns additional or fewer elements on the session info API call after upgrades. 
This PR checks only the requested keys (`thresholds`) to exist in both snapshots and ignores any other changes in the API response.
Fixes #47.
Tested with the snapshot_load_compare.py example script.

feat: validate only requested keys for session_stats comparison

---

panos_upgrade_assurance/firewall_proxy.py

Assumed wrong API response format for devices with more than 1 Panorama host configured.
Panorama connectivity check throws an exception about malformed device response.
Run on hosts with different versions.

fix(FirewallProxy): wrong parsing for 2 Panorama hosts

---

docs/panos-upgrade-assurance/installation.mdx
panos_upgrade_assurance/check_firewall.py

Without the codeset information some hosts raise `locale.Error: unsupported locale setting` exception. 
This change sets `en_US.UTF-8` locale to be used.
Tested with example scripts on repo.

fix: locale setting need codeset to be set

---

docs/panos-upgrade-assurance/api/check_firewall.md
panos_upgrade_assurance/check_firewall.py

Get IPSec tunnel information with dict get method to avoid raising KeyError.
See the attached issue for details.
Fixes #70 
Tested with example scripts on repo

fix: IPSec KeyError on ip_sec_tunnels snapshot

---

docs/panos-upgrade-assurance/api/check_firewall.md
examples/readiness_checks/run_readiness_checks.py
panos_upgrade_assurance/check_firewall.py

When HA pair is partially upgraded HA status reports non-functional on the non-upgraded peer which results in failure to identify the active peer. This adds an option to ignore `non-functional` state in `check_ha_status` and `check_is_ha_active` checks.
Makes it possible to identify active peer on HA pair with non-functional state.
Tested with example scripts on repo and Ansible playbooks.

feat: ignore non-functional state in ha status and active checks

---

.github/workflows/close_pr.yml
.github/workflows/lint_pr_title.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/sub_pandev.yml

Adds an automatic PR into PAN.DEV repository with updated documentation.
Each release might require official documentation updates. A nice-to-have is a PREVIEW PR with documentation that will get merged to `main`.
This PR will introduce:
- A *PREVIEW* PR to PAN.DEV for each PR created in this repository
- A PR to PAN.DEV for each release published in this repository
- If a PR get's merged or closed the *PREVIEW* PR will be automatically closed
- If a new release is published before the PR in PAN.DEV gets merged, the pending PR (all of them) will be closed and a new one with current documentation will be created. 
All workflows tested on a separate repository

ci: add PAN.DEV pr creation

---

panos_upgrade_assurance/snapshot_compare.py

This change avoids an unhandled exception when no common keys exist in snapshot comparison and generate an output with added/missing keys.
Also fixes #82 where snapshot comparison properties are getting ignored occasionally. 
In snapshot comparison when snapshots to be compared had no common keys, this resulted in an un-handled lndexError exception given below. This was happening mostly on arp table comparison where two snapshots had no common entries. 
```python
Traceback (most recent call last):
File "snapshot_load_compare.py", line 39, in <module>
report = compare.compare_snapshots(reports)
File "/Users/akose/Development/paloalto/pan-os-upgrade-assurance/panos_upgrade_assurance/snapshot_compare.py", line 126, in compare_snapshots
{report_type: …
```

fix: snapshot comparison with no common keys

---

docs/panos-upgrade-assurance/api/check_firewall.md
panos_upgrade_assurance/check_firewall.py

Adds a flag to CheckFirewall to skip locale enforcement to en_US.UTF-8 which will run with the default locale settings on the host running the library. 
Fixes #81 
Tested with local example script and ansible playbook.

feat: add option to skip locale enforcement

---

pyproject.toml

Downgrade black
Latest black release causes the following error (reproducible both locally and during CI run)

ci: downgrade black

---

panos_upgrade_assurance/snapshot_compare.py
tests/test_snapshot_compare.py

This PR addresses an issue encountered when comparing ARP tables using the `calculate_diff_on_dicts` function, specifically when `ttl` values are present as integers. Previously, the function would raise a `WrongDataTypeException` due to its inability to handle integer values, causing failures in scripts that rely on comparing ARP table entries.
Addresses #152 
The `calculate_diff_on_dicts` function was limited to handling strings and dictionaries, overlooking the possibility of integer values such as those found in `ttl` fields of ARP tables. This limitation led to a `WrongDataTypeException` when the function encountered an integer `ttl` value, particularly evident when comparing ARP tables with single entries.
To resolve this issue, the comparison logic within `calculate_diff_on_dicts` …

fix: calculate_diff_on_dicts to Support Integer Values for ARP Table ttl

---

docs/panos-upgrade-assurance/api/firewall_proxy.md
docs/panos-upgrade-assurance/api/snapshot_compare.md
docs/panos-upgrade-assurance/configuration_details.mdx
examples/readiness_checks/run_readiness_snapshot.py
examples/report/fw1.snapshot
examples/report/fw2.snapshot
panos_upgrade_assurance/firewall_proxy.py
panos_upgrade_assurance/snapshot_compare.py
tests/snapshots.py
tests/test_firewall_proxy.py
tests/test_snapshot_compare.py

The route table snapshot was missing entries when ECMP routes (differed only by next-hop) were present. This was because dict key generation was based only on VR name, destination CIDR and interface (if applicable). This PR adds next-hop IP address or name to dict key, so the keys are unique every time.
#56 
It has been tested with example python scripts.

fix: route snapshot missing entries fix

---

.github/workflows/release.yml
.github/workflows/sub_unittest.yml

CI Release workflow failed requiring write access for contents. 
https://github.com/PaloAltoNetworks/pan-os-upgrade-assurance/actions/runs/8073836898
CI changes

ci: fix release unittests permissions

---

panos_upgrade_assurance/firewall_proxy.py

This PR closes #158 .
FWs in PAN-s 11.0 and later removed a line from the `show panorama-status` op command output:
Pre-version 11.0:
```
<Panorama Server 1 : 10.10.10.5
Connected     : yes
HA state      : Active
Panorama Server 2 : 10.10.10.6
Connected     : yes
HA state      : Passive>.
```
Version >=11.0:
```
<Panorama Server 1 : 10.10.10.5
Connected     : yes
HA state      : Active
Panorama Server 2 : 10.10.10.6
Connected     : yes
HA state      : Passive>.
```
This resulted in two different list lengths that did no match the condition properly.
Support for PAN-OS >=11.0 for `is_panorama_connected` check .
Local Example with two different versions:
```
python3 run_readiness_checks.py -d <pan_os_v11> -u admin -p <MY_PASS>
['Panorama Server 1 : 10.10.10.5', '    Connected     : yes', ' …
```

fix(firewall_proxy/is_panorama_connected): Added fix for panorama check for FWs in version PAN-OS 11 or later

---

panos_upgrade_assurance/firewall_proxy.py
tests/test_firewall_proxy.py

Fixes `FirewallProxy.get_jobs()` method to handle jobs response with a single entry as dict (instead of list).
See #164 for details.
Fixes #164 and #124 
Tested on firewalls with example scripts.

fix: get_jobs exception when single job entry

---

panos_upgrade_assurance/firewall_proxy.py
tests/test_firewall_proxy.py

Release v0.3.4 introduced BGP peers information to snapshots. Function didn't handle well a situation where the firewalls didn't have any BGP peers. Added additional _if statement_ to handle that.
As above.
Tested with examples present in the repo.

fix: Failing snapshots of FWs with no BGP peers

---

.releaserc

Remove the custom release version calculation rules: feat -> patch, braking -> minor, feat(MAJOR) -> major.
There were no braking changes recently, we can assume the code is major enough not to produce tons of major versions. 
We also need to align the rules for calculating releases with [`pan-os-ansible`](https://github.com/PaloAltoNetworks/pan-os-ansible) project.

chore: standard semantic release rules

---

pyproject.toml

Missing dependency in pyproject.toml causing panos_upgrade_assurance module not found error.
This is a critical issue which makes panos_upgrade_assurance fail to run.
Had to fix it to a specific version "4.6.3", otherwise it breaks pydoc-markdown which have conflicting dependencies. We need to take care of this with #171 
```python
Error: [Traceback (most recent call last):
File "<string>", line 7, in <module>
File "/usr/local/lib/python3.10/site-packages/panos_upgrade_assurance/firewall_proxy.py", line 3, in <module>
from panos_upgrade_assurance.utils import interpret_yes_no
File "/usr/local/lib/python3.10/site-packages/panos_upgrade_assurance/utils.py", line 5, in <module>
from typing_extensions import TypeAlias
ModuleNotFoundError: No module named 'typing_extensions'
```
Tested …

fix: typing-extensions dependency missing

---

docs/panos-upgrade-assurance/api/check_firewall.md
panos_upgrade_assurance/check_firewall.py
tests/test_check_firewall.py

This PR adds support for Proxy IDs to `ipsec_tunnel_status` readiness check.
`ipsec_tunnel_status` check now accepts a list of `proxy_ids` to check tunnel status against the provided list, or it checks for all configured Proxy IDs if not provided.
By default it will return success if any Proxy ID is in active state for the ipsec tunnel or `require_all_active` flag can be set to require all Proxy IDs to be in active state.
`ipsec_tunnel_status` readiness check didn't work if IPSec tunnel was configured with Proxy IDs.
With this enhancement it checks for all the proxy ids for the given tunnel name and returns success if any is in active state. It is also possible to provide a list of proxy ids to limit the check on specific Proxy IDs.
Tested with the written unittests.
- New feature …

feat: ipsec_tunnel_status check Proxy ID support

---

.github/workflows/_discover_python_ver.yml
.github/workflows/_docker.yml
.github/workflows/close_pr.yml
.github/workflows/close_pr_workflow_run.yml
.github/workflows/pr.yml
.github/workflows/pr_workflow_run.yml
.github/workflows/publish_documentation.yml
.github/workflows/publish_python_package.yml
.github/workflows/release.yml
.github/workflows/sub_docs.yml
.github/workflows/sub_format.yml
.github/workflows/sub_unittest.yml

GitHub recommends pinning actions to a full length commit SHA, as this is currently the only method of using an action as an immutable release.
For more information refer to: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

ci: Pin GitHub Actions

---

docs/panos-upgrade-assurance/api/firewall_proxy.md
panos_upgrade_assurance/firewall_proxy.py
tests/test_firewall_proxy.py

Fixes KeyError exception thrown if job entry doesnot have an id for jobs check, typically for Failed-Job type. 
Response doesnot include jobs with no job id now.
Tested with unit tests.

fix: get_jobs with missing job id entries

---

.github/actions/discover_python_version/action.yml
.github/workflows/sub_docs.yml
Makefile
panos_upgrade_assurance/utils.py
pyproject.toml
requirements-docs.txt

* converted depedency version contraints to >=,<
* removed pydoc-markdown dependency temporarily until we find a better approach - it restricts dependency updates since its not being maintained anymore 
* removed fixed version typing_extensions and databind deps
Temp remediation for #171 
pytest
- deps

fix: loosen deps constraints and remove pydoc-markdown

---

docs/panos-upgrade-assurance/api/check_firewall.md
docs/panos-upgrade-assurance/api/firewall_proxy.md
docs/panos-upgrade-assurance/api/utils.md
examples/readiness_checks/run_readiness_checks.py
examples/readiness_checks/run_readiness_snapshot.py
examples/report/fw1.snapshot
examples/report/fw2.snapshot
examples/report/snapshot_load_compare.py
panos_upgrade_assurance/check_firewall.py
panos_upgrade_assurance/firewall_proxy.py
panos_upgrade_assurance/snapshot_compare.py
panos_upgrade_assurance/utils.py
tests/test_check_firewall.py
tests/test_firewall_proxy.py

adding `global_jumbo_frame` snapshot type and readiness check.
with the `global_jumbo_frame` snapshot it is possible to compare global jumbo frame configuration pre and post upgrade.
And the readiness check allows to check if global jumbo frame configuration is in the expected mode which gets `mode: True` or `mode: False` attribute as an input.
Tested with local scripts and local ansible playbook

feat: global jumbo frame snapshot and readiness check

---

docs/panos-upgrade-assurance/api/check_firewall.md
docs/panos-upgrade-assurance/api/firewall_proxy.md
docs/panos-upgrade-assurance/configuration_details.mdx
examples/low_level_methods/run_low_level_methods.py
examples/readiness_checks/run_readiness_checks.py
panos_upgrade_assurance/check_firewall.py
panos_upgrade_assurance/firewall_proxy.py
panos_upgrade_assurance/utils.py
tests/test_check_firewall.py
tests/test_firewall_proxy.py

`environmentals` readiness check added to check for any alarms in the `show system environmentals` output. Check optionally accepts "components" to only check alarms in specific components like fan or power-supply.
Unit tests and on firewalls with ansible playbook.

feat: system environmentals readiness check

---

docs/panos-upgrade-assurance/api/check_firewall.md
docs/panos-upgrade-assurance/api/firewall_proxy.md
docs/panos-upgrade-assurance/configuration_details.mdx
examples/low_level_methods/run_low_level_methods.py
examples/readiness_checks/run_readiness_checks.py
panos_upgrade_assurance/check_firewall.py
panos_upgrade_assurance/firewall_proxy.py
panos_upgrade_assurance/utils.py
tests/test_check_firewall.py
tests/test_firewall_proxy.py

Implement data plane and management plane cpu readiness checks:
* `mp_cpu_utilization` readiness check implemented that checks if management plane
cpu utilization passes a given threshold compared to average of last 1 minute.
* `dp_cpu_utilization` readiness check implemented that checks if dataplane cpu
utilization passes a given threshold during the last X minutes.
Tested with unit tests.

feat: data plane and management plane cpu readiness checks

---

panos_upgrade_assurance/utils.py
pyproject.toml

typing_extensions added as a dependency when python version <3.10 since we are only using TypeAlias from typing_extensions which is added to typing in python 3.10. 
Import for TypeAlias updated according to the running python version.
It was breaking when trying to import TypeAlias from typing_extensions for python >= 3.10 because typing_extensions is not a dependency but TypeAlias was being imported from typing_extensions.
Updated typing_extensions dependency according to the python version and also TypeAlias import is conditionally done from typing when python version is >3.10.
This also broke Docker image which is working with python 3.10.
Tested locally with virtualenvs in different python versions.

fix: typing_extensions dependency on python <3.10

---

Dockerfile

Users reported the upgrade assurance docker image is failing to run within XSOAR with `ModuleNotFoundError: No module named 'typing_extensions'` 
The docker image is currently set to `3.10` but `TypeAlias` is implemented in 3.12, so I think we need to bump it.

fix: Bump Dockerfile python version
